### ISSUE TITLE
Risk of data loss with `Access server` button?

### ISSUE THREAD

**Issue by Chiil** [2i2c-org/pilot#20]
What happens if I click the `access server` button from one of the student accounts in the `hub/admin` page? Can I take control of their notebook, or are we both editing in the same file? This seems like a useful option for remote help, but only if it comes without the risk of data loss?

**Comment by choldgraf** [comment]
I believe that you will now be controlling their server *as if* it was themselves doing it. So if you change things, save things, etc then it'll save on _their_ filesystem.

As a general rule, we try not to edit anything and if we do it's only if the student is watching us do it, so that we don't confuse folks. Does that make sense?
