### ISSUE TITLE
.Call error when trying to use saved output in R Studio

### ISSUE THREAD

**Issue by caitlinkroeger** [2i2c-org/pilot#82]
The following error only occurs if I try to use VAST package plotting functions from saved model output if the server has timed out or R Studio crashes or my internet has lost connection for a bit -  it doesn’t occur if I use the functions right after the model runs. I'm a bit confused in deciphering the error message and wondering if anyone might have a better idea if this is an issue with the VAST package or with using the server or both? Maybe this question is better directed toward the creator of the VAST package? Thanks in advance! 

Error in .Call("TMBconfig", e, as.integer(1), PACKAGE = DLL) : 
  "TMBconfig" not available for .Call() for package "VAST_v13_0_0"

**Comment by choldgraf** [comment]
Hmmm - this is probably outside of the knowledge set of our team, we don't have a lot of experience with the R ecosystem, and this feels like something that is package-specific rather than a JupyterHub issue, so will be hard for us to help. Sorry!

I'll close this, but if you think it's something related to 2i2c infrastructure feel free to re-open!
